'use strict';

export const allowedPromotionFields = [
  'name',
  'description',
  'terms',
  'active',
  'validFrom',
  'validTo',
  'imageUrl',
  'conditions',
  'type',
  'status',
  'targetSegment',
  'targetRoles',
  'maxUsesGlobal',
  'maxUsesPerUser',
  'budget',
  'priority',
  'stackable',
  'applicableServices',
  'internalNote',
  'tags',
];

export const allowedServiceFields = [
  'name',
  'description',
  'type',
  'price',
  'currency',
  'category',
  'status',
  'active',
  'validFrom',
  'validTo',
  'imageUrl',
  'terms',
  'minBalance',
  'maxUsesPerUser',
  'totalUsesLimit',
  'targetRoles',
  'tags',
  'discount',
  'internalNote',
  'requiresVerifiedEmail',
];
